In [1]:
import os
import pandas as pd
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score,recall_score, f1_score,roc_auc_score

In [2]:
# no ATAC
y_true = np.load('../model/pred_results_ablation/no_ATAC_label.npy')
y_pred = np.load('../model/pred_results_ablation/no_ATAC_predict.npy')

y_score = y_pred.argmax(axis=1)       
test_label = y_true.argmax(axis=1)                         
y_score_pro = y_pred # (212, 2)
y_one_hot = y_true
y_score_one_hot = to_categorical(y_score)

obj1 = confusion_matrix(test_label, y_score)
print('confusion_matrix\n', obj1)
print('accuracy:{}'.format(accuracy_score(test_label, y_score)))
print('precision:{}'.format(precision_score(test_label, y_score)))
print('recall:{}'.format(recall_score(test_label, y_score)))
print('f1-score:{}'.format(f1_score(test_label, y_score)))

from sklearn.metrics import roc_curve, auc
fpr_xgb, tpr_xgb, thresholds = roc_curve(y_one_hot.ravel(),y_score_pro.ravel())   
auc_xgb = auc(fpr_xgb, tpr_xgb)
print("AUC : ", auc_xgb)

confusion_matrix
 [[252  62]
 [ 91 237]]
accuracy:0.7616822429906542
precision:0.7926421404682275
recall:0.7225609756097561
f1-score:0.7559808612440191
AUC :  0.8381396725575256


In [3]:
# no Seq
y_true = np.load('../model/pred_results_ablation/no_Seq_label.npy')
y_pred = np.load('../model/pred_results_ablation/no_Seq_predict.npy')

y_score = y_pred.argmax(axis=1)       
test_label = y_true.argmax(axis=1)                         
y_score_pro = y_pred # (212, 2)
y_one_hot = y_true
y_score_one_hot = to_categorical(y_score)

obj1 = confusion_matrix(test_label, y_score)
print('confusion_matrix\n', obj1)
print('accuracy:{}'.format(accuracy_score(test_label, y_score)))
print('precision:{}'.format(precision_score(test_label, y_score)))
print('recall:{}'.format(recall_score(test_label, y_score)))
print('f1-score:{}'.format(f1_score(test_label, y_score)))

from sklearn.metrics import roc_curve, auc
fpr_xgb, tpr_xgb, thresholds = roc_curve(y_one_hot.ravel(),y_score_pro.ravel())   
auc_xgb = auc(fpr_xgb, tpr_xgb)
print("AUC : ", auc_xgb)

confusion_matrix
 [[216  98]
 [166 162]]
accuracy:0.5887850467289719
precision:0.6230769230769231
recall:0.49390243902439024
f1-score:0.5510204081632654
AUC :  0.6189186828543978


In [4]:
# no BiGRU
y_true = np.load('../model/pred_results_ablation/no_BiGRU_label.npy')
y_pred = np.load('../model/pred_results_ablation/no_BiGRU_predict.npy')

y_score = y_pred.argmax(axis=1)       
test_label = y_true.argmax(axis=1)                         
y_score_pro = y_pred # (212, 2)
y_one_hot = y_true
y_score_one_hot = to_categorical(y_score)

obj1 = confusion_matrix(test_label, y_score)
print('confusion_matrix\n', obj1)
print('accuracy:{}'.format(accuracy_score(test_label, y_score)))
print('precision:{}'.format(precision_score(test_label, y_score)))
print('recall:{}'.format(recall_score(test_label, y_score)))
print('f1-score:{}'.format(f1_score(test_label, y_score)))

from sklearn.metrics import roc_curve, auc
fpr_xgb, tpr_xgb, thresholds = roc_curve(y_one_hot.ravel(),y_score_pro.ravel())   
auc_xgb = auc(fpr_xgb, tpr_xgb)
print("AUC : ", auc_xgb)

confusion_matrix
 [[248  66]
 [ 98 230]]
accuracy:0.7445482866043613
precision:0.777027027027027
recall:0.7012195121951219
f1-score:0.7371794871794871
AUC :  0.8105183858852301


In [5]:
# no Transformer
y_true = np.load('../model/pred_results_ablation/no_Transformer_label.npy')
y_pred = np.load('../model/pred_results_ablation/no_Transformer_predict.npy')

y_score = y_pred.argmax(axis=1)       
test_label = y_true.argmax(axis=1)                         
y_score_pro = y_pred # (212, 2)
y_one_hot = y_true
y_score_one_hot = to_categorical(y_score)

obj1 = confusion_matrix(test_label, y_score)
print('confusion_matrix\n', obj1)
print('accuracy:{}'.format(accuracy_score(test_label, y_score)))
print('precision:{}'.format(precision_score(test_label, y_score)))
print('recall:{}'.format(recall_score(test_label, y_score)))
print('f1-score:{}'.format(f1_score(test_label, y_score)))

from sklearn.metrics import roc_curve, auc
fpr_xgb, tpr_xgb, thresholds = roc_curve(y_one_hot.ravel(),y_score_pro.ravel())   
auc_xgb = auc(fpr_xgb, tpr_xgb)
print("AUC : ", auc_xgb)

confusion_matrix
 [[221  93]
 [ 84 244]]
accuracy:0.7242990654205608
precision:0.7240356083086054
recall:0.7439024390243902
f1-score:0.7338345864661655
AUC :  0.8035696955580788
